### ISSUE TITLE
Frontend shouldn't need to grow the WASM Memory

### ISSUE THREAD

**Issue by CryZe** [torch2424/wasmBoy#50]
This commit changed the memory base to 0, causing it to only preallocate 1 page: https://github.com/torch2424/wasmBoy/commit/eec0552de0eb5682909e530e44ac382595633374

JS / Rust shouldn't need to grow the memory though. This can either be changed back or AssemblyScript can just grow the memory itself. This also means that the call can be removed in JS altogether.

**Comment by torch2424** [comment]
Ahhhh so `--memoryBase` was something added by @dcodeIO to Assemblyscript because I asked him nicely :) 

Essentially, it would set up the default location where the assemblyscript buffer would put data. So forexample, when assemblyscript will construct strings or arrays, it will allocate data their by default.

So it would make sense if they grew the memory there for us when I did that.

But, I had plans in #7 to only grow the memory based on the [Cartridge MBC type](http://gbdev.gg8.se/wiki/articles/Memory_Bank_Controllers), Therefore, I would need to move around this memory base and things if I went ahead with this.

 I think to resolve this, I can simply grow the memory conditionally in the [cpu initialize][https://github.com/torch2424/wasmBoy/blob/master/wasm/cpu/cpu.ts#L119] function.

would that work out? And sorry I keep messing up memory stuff for you 😢 I feel bad about it!

**Comment by CryZe** [comment]
To me it sounds like asc needs `--minMemory` or something, cause it seems like that controls where asc allocates its strings and co. and also how many pages are being used in the first place. So it should probably be two separate options.

**Comment by CryZe** [comment]
Also initialize is probably too late, as you want to load the rom before that. You can however just have it "floating" outside of any function and AssemblyScript will execute it whenever the wasm gets instantiated.

**Comment by torch2424** [comment]
Oh yeah, I can ask for a `--min-memory` or something of the sort. 

And you are right initialize would be too late :(

And could you elaborate a bit more on "floating"?

And lastly, how about we try this: on initialize, we grow the memory to max wasnboy will support, and after we load the room and start the game, we shrink back to the size we would need? That way we are not using more memory while playing the game? Only when we load it and get things set up?

And just to make sure, are you only interfacing with wasmBoy through the wasm? If so, that's super rad, I've been trying to do all the abstractions on the js side, but if that's the case, in my next code cleanup, I'll move those abstractions down to wasm, or at least plan to do that :)

**Comment by CryZe** [comment]
> And could you elaborate a bit more on "floating"?
```typescript
someFunctionCall();

function hi() { }
function someFunctionCall() {}
```
This calls someFunctionCall without you needing to explicitly needing to call it from JS. Essentially stuff like this: https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/while.ts will immediately get executed.

> we shrink back to the size we would need?
You can't shrink wasm memory atm.

> are you only interfacing with wasmBoy through the wasm?
I'm not quite sure what you mean by that. The only things I don't go through the public interface is for copying memory over (like copying the ROM in, and copying the frame buffer out)

**Comment by torch2424** [comment]
> Floating

Oh yeah, Let's go with the "floating" route, makes the most sense.

> You can't shrink wasm memory atm.

Oh yeah, duh, I completely forgot haha! Well honestly, that kind of invalidates #7 . Since essentially, I was hoping to only scale up if a user loaded a larger game than the last. We would have to do all kinds of re-instantiaion to shrink, which would kind of be worst than using too much memory (especially since were only talking like a 4MB difference :p)

> You can read the code, it's just the main.rs

Oh yeah, you are only going through the wasm. I put the "core" you could say in webassembly, and the "API" I intended people to use in JS. I didn't expect cool people like you to be able to run it in rust haha! So I had the idea you were still using parts of the JS for some reason. Essentially, what I'm trying to say is, now that I know this, I'm going to also focus on documenting and cleaning up the API for the "core" and not just the JS "API", since it is not the final public facing abstraction I had planned it to be 😄

**Comment by torch2424** [comment]
I'm gonna grab dinner, and then I'll come back and move the wasm pages to wasm for you 😄

**Comment by torch2424** [comment]
Okay, so not going to lie, I'm kind of tired, is tommorow okay? Haha!

**Comment by dcodeIO** [comment]
Fwiw, the compiler uses `--memoryBase` as the start offset of statically generated memory segments, like strings, as described above. From there on, it keeps track of the amount of pages required to store the static data and sets the initial number of pages to the respective size. So, for example, if `--memoryBase` is 65536+1, the compiler emits an initial number of pages of 2 because the offset overlaps into the second page. Now, if static data increases the offset beyond 131072+1, it emits an initial number of pages of 3 etc. The compiler also generates a `HEAP_BASE` global that points at the first 8b aligned offset after static data ([see](https://github.com/AssemblyScript/assemblyscript/blob/master/src/compiler.ts#L305)). As always, just drop me a note if you need another option :)

**Comment by torch2424** [comment]
Yoooo!

Thanks for joining the party @dcodeIO !

Cool yeah, glad I understood the `--memoryBase` option you had made :) 

What I may do is, as you said, make some functions to grow for a certain ROM MBC Type, that simply return if there is enough space, or allocate as you said if needed :)

Thanks for jumping in on the conversation, it was super helpful, and I'll leave a note in #7

**Comment by dcodeIO** [comment]
If you need to ressize memory, you could also give one of the other two allocators a try, namely tlsf and buddy. These are also capable of freeing memory, for example if a block of memory might have to be resized, through `free_memory`.

**Comment by torch2424** [comment]
@dcodeIO Oooooo that's a really good idea. I'll have to think if adding a KB to the binary is worth saving the 4MB of RAM in the browser haha!
